name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
            OUTPUT: CHANGES.md
            GITHUB_REPO: ${{ github.repository }}

  meta:
    name: Determine Release Metadata
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag="v$(date +%Y%m%d)-manual"
            echo "tag=$tag" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          if $is_release; then
            tag="${GITHUB_REF#refs/tags/}"
          else
            latest_tag=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v0.0.0")
            commit_short=$(git rev-parse --short HEAD)
            tag="${latest_tag}-${commit_short}-$(date +%Y%m%d)"
          fi
          
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "is_release=$is_release" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: [changelog, meta]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            compress_cmd: "zip -r -9"
            ext: zip
            
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            compress_cmd: "zip -r -9"
            ext: zip
            
          - os: macos-latest
            platform: osx       
            arch: x64
            compress_cmd: "zip -r -9"
            ext: zip
         
          - os: macos-latest
            platform: osx
            arch: arm64
            compress_cmd: "zip -r -9"
            ext: zip
            
          - os: windows-latest
            platform: win
            arch: x64
            compress_cmd: "7z a -tzip"
            ext: zip
            
          - os: windows-latest
            platform: win
            arch: arm64
            compress_cmd: "7z a -tzip"
            ext: zip
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          config-file: NuGet.config

      - name: Restore Dependencies
        run: dotnet restore
        env:
          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

      - name: Build Solution
        run: dotnet publish -c Release -r ${{ matrix.platform }}-${{ matrix.arch }}

      - name: Unified ZIP Packaging 
        shell: bash
        run: |
            BUILD_DIR="bin/AnyCPU/Release/${{ matrix.platform }}-${{ matrix.arch }}/publish"
            OUTPUT_FILE="MFAAvalonia-${{ needs.meta.outputs.tag }}-${{ matrix.platform }}-${{ matrix.arch }}.zip"
            TEMP_DIR="${{ github.workspace }}/temp_pkg"

            # 清理并创建临时目录
            rm -rf $TEMP_DIR
            mkdir -p $TEMP_DIR

            # 复制发布文件（排除临时目录）
            cp -r $BUILD_DIR/* $TEMP_DIR/

            # 执行压缩
            cd $TEMP_DIR
            ${{ matrix.compress_cmd }} $OUTPUT_FILE *
            sha256sum $OUTPUT_FILE > $OUTPUT_FILE.sha256

            # 移动产物到构建目录
            mv $OUTPUT_FILE $BUILD_DIR/
            mv $OUTPUT_FILE.sha256 $BUILD_DIR/

            # 清理临时文件
            rm -rf $TEMP_DIR

      - name: Upload ZIP Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            bin/AnyCPU/Release/${{ matrix.platform }}-${{ matrix.arch }}/*.zip
            bin/AnyCPU/Release/${{ matrix.platform }}-${{ matrix.arch }}/*.sha256

  release:
    name: Create Release
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    runs-on: ubuntu-latest
    needs: [meta, build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Checksums
        shell: bash
        run: |
          cd artifacts
          find . -type f -name "*.tar.gz" -o -name "*.zip" | while read file; do
            sha256sum "$file" > "$file.sha256"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.meta.outputs.tag }}
          body: ${{ needs.changelog.outputs.release_body }}
          files: |
            artifacts/**/*
          draft: false
          prerelease: ${{ contains(needs.meta.outputs.tag, '-') }}
          generate_release_notes: true
          replace_existing: true
        env:
          TOKEN: ${{ secrets.MFA_TOKEN }}

